/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazPropuesta;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Dhtey
 */
public class InterfazPO extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPO
     */
    public InterfazPO() {
        initComponents();
        centrado();
    }

    /**
     * Method to center the interface
     */
    public void centrado() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPO = new javax.swing.JLabel();
        numPO = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        fechaEmision = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        procesos = new javax.swing.JLabel();
        tfNumPO = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        tfFechaEmision = new javax.swing.JTextField();
        tfCantidad = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        CBProceso1 = new javax.swing.JCheckBox();
        CBProceso2 = new javax.swing.JCheckBox();
        CBProceso3 = new javax.swing.JCheckBox();
        CBProceso4 = new javax.swing.JCheckBox();
        CBProceso5 = new javax.swing.JCheckBox();
        CBProceso6 = new javax.swing.JCheckBox();
        CBProceso7 = new javax.swing.JCheckBox();
        CBProceso8 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoPO.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        infoPO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoPO.setText("Informacion PO");

        numPO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numPO.setText("Numero PO:");

        cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cliente.setText("Cliente:");

        fechaEmision.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaEmision.setText("Fecha Emision:");

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad.setText("Cantidad:");

        descripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripcion.setText("Descripcion:");

        procesos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        procesos.setText("Proceso");

        tfNumPO.setEditable(false);
        tfNumPO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNumPO.setText("###########");
        tfNumPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumPOActionPerformed(evt);
            }
        });

        tfCliente.setEditable(false);
        tfCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCliente.setText("@@@@@@@@@");

        tfFechaEmision.setEditable(false);
        tfFechaEmision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfFechaEmision.setText("##/##/####");

        tfCantidad.setEditable(false);
        tfCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCantidad.setText("##########");

        tfDescripcion.setEditable(false);
        tfDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfDescripcion.setText("@@@@@@@");

        CBProceso1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso1.setText("Proceso 1");
        CBProceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBProceso1ActionPerformed(evt);
            }
        });

        CBProceso2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso2.setText("Proceso 2");
        CBProceso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBProceso2ActionPerformed(evt);
            }
        });

        CBProceso3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso3.setText("Proceso 3");

        CBProceso4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso4.setText("Proceso 4");

        CBProceso5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso5.setText("Proceso 5");

        CBProceso6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso6.setText("Proceso 6");

        CBProceso7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso7.setText("Proceso 7");

        CBProceso8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBProceso8.setText("Proceso 8");

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox6.setText("Proceso 9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumPO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaEmision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFechaEmision)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCantidad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 309, Short.MAX_VALUE)
                .addComponent(procesos)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(infoPO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBProceso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBProceso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBProceso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBProceso4)
                    .addComponent(CBProceso5)
                    .addComponent(CBProceso6))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox6)
                    .addComponent(CBProceso8)
                    .addComponent(CBProceso7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(infoPO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPO)
                    .addComponent(cantidad)
                    .addComponent(tfNumPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente)
                    .addComponent(descripcion)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaEmision)
                    .addComponent(tfFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(procesos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBProceso1)
                    .addComponent(CBProceso4)
                    .addComponent(CBProceso7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBProceso2)
                    .addComponent(CBProceso5)
                    .addComponent(CBProceso8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBProceso3)
                    .addComponent(CBProceso6)
                    .addComponent(jCheckBox6))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumPOActionPerformed

    private void CBProceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBProceso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBProceso1ActionPerformed

    private void CBProceso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBProceso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBProceso2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBProceso1;
    private javax.swing.JCheckBox CBProceso2;
    private javax.swing.JCheckBox CBProceso3;
    private javax.swing.JCheckBox CBProceso4;
    private javax.swing.JCheckBox CBProceso5;
    private javax.swing.JCheckBox CBProceso6;
    private javax.swing.JCheckBox CBProceso7;
    private javax.swing.JCheckBox CBProceso8;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel fechaEmision;
    private javax.swing.JLabel infoPO;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel numPO;
    private javax.swing.JLabel procesos;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfFechaEmision;
    private javax.swing.JTextField tfNumPO;
    // End of variables declaration//GEN-END:variables
}
